#!/usr/bin/env bash
# Checking CL paramenters

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# Assign parameters to variables

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Disable strict host key check

scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if the transfer was successful
if [ $? -eq 0 ]
then
        echo "FILE TRANSFERED SUCCESSFULLY"
else
        echo "FILE TRANSFER FAILED"
fi
