#!/usr/bin/env bash
# Displays the content of the file '/etc/passwd'
# Use cut to extract the desired fields and save them to a temporary file
cut -d ':' -f1,3,6 /etc/passwd > /tmp/passwd_tmp

# Read each line of the temporary file using a while loop
while read -r line; 
do
    # Print the extracted fields
    echo "$line"
done < /tmp/passwd_tmp

# Remove the temporary file
rm /tmp/passwd_tmp