#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while

# Initialize a counter
counter=0

# Use a while loop to display "Best School"
until [ $counter -eq 10 ]
do
    echo "Best School"
    ((counter++))
done