#!/usr/bin/env bash
# This script displays "Best School" 10 times with alternate displays

# Initialize a counter
counter=1

# Use a while loop to display numbers from 1 to 20
while [ $counter -le 20 ]
do
    # Use a case statement to check for specific iterations
    case $counter in
        4)
            echo $counter
            echo "bad luck from China"
            ;;
        9)
            echo $counter
            echo "bad luck from Japan"
            ;;
        17)
            echo $counter
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    
    # Increment the counter
    ((counter++))
done